### ISSUE TITLE
The option to enable achievements is not working

### ISSUE THREAD

**Issue by Marcioxm** [xADDBx/ToyBox-Wrath#19] opened 2024-08-07 04:20 UTC
### Description of the bug

I'm trying to get the achievement for killing the elemental in the tutorial, but when I manage to kill it, it doesn't work, both on normal and later difficulties.

### Steps To Reproduce

qualquer achievement

### Toybox Version

1.5.29

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

**Comment by xADDBx** [comment] 2024-08-15 00:30
Save to debug? Logs?

**Comment by pehala** [comment] 2024-08-23 11:38
I encountered the same issue. Killed elemental on Core and it did not trigger. When inspecting achivements I found that it is disabled (every achievement seems to be).

ToyBox: 1.5.42
WOTR: 2.3.3k

I checked gameLog and apart from a lot of Missing binding errors, I found this:
```
[417.8342 - History.Area]: 21:59:46 16.08.4715 - [History.Area] CR5_WaterElementalLarge_LabyrinthBoss (4518955732be42ecbe41221001163c2a)unit dies
[417.8357 - Etudes]: Completing etude: Labyrinth_SideBoss_WaterElemental_Audio
[417.8367 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:CompletionInProgress
[417.8387 - Etudes]: Starting etude: 37_FirstBigEnemy
[417.8393 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:IsAttached
[417.8393 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:State.Started
[417.8467 - History.Area]: 21:59:46 16.08.4715 - [History.Area] Delete_WaterElemCorpse (000a7bea18fd40838d63a850dda49bc6)cutscene started
[417.8488 - Etudes]: Updating etude system
[417.8498 - Etudes]: Etude stopping: Labyrinth_SideBoss_WaterElemental_Audio
[417.8498 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:stoping
[417.8508 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:IsCompleted
[417.8508 - Etudes]: Finally completed etude: Labyrinth_SideBoss_WaterElemental_Audio
[417.8538 - Etudes]: Etude playing: 37_FirstBigEnemy
[417.8538 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:IsPlaying
[417.9086 - Default]: Unit leave combat: Unit[StartGame_Player_Unit]#9b22011c-06cf-4c17-8899-8b9dec6a77c4
[417.9096 - Default]: Unit leave combat: Unit[Seelah_Companion]#4360
[417.9096 - Default]: Unit leave combat: Unit[Camelia_Companion]#4444
[417.9096 - Default]: Unit leave combat: Unit[Lann_Companion]#454A
[417.9096 - Etudes]: Updating etude system
[417.9442 - History.Combat]: 21:59:46 16.08.4715 - [History.Combat] party combat finished
[417.9477 - TBM]: Reset tryToInitialize=False isPartyCombatStateChanged=True
[417.9492 - TechArt]: Camera at the end: (31.6, 32.6, 104.9)
```
Is there anything else you need to investigate it?

**Comment by xADDBx** [comment] 2024-08-25 02:32
> I encountered the same issue. Killed elemental on Core and it did not trigger. When inspecting achivements I found that it is disabled (every achievement seems to be).
> 
> ToyBox: 1.5.42 WOTR: 2.3.3k
> 
> I checked gameLog and apart from a lot of Missing binding errors, I found this:
> 
> ```
> [417.8342 - History.Area]: 21:59:46 16.08.4715 - [History.Area] CR5_WaterElementalLarge_LabyrinthBoss (4518955732be42ecbe41221001163c2a)unit dies
> [417.8357 - Etudes]: Completing etude: Labyrinth_SideBoss_WaterElemental_Audio
> [417.8367 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:CompletionInProgress
> [417.8387 - Etudes]: Starting etude: 37_FirstBigEnemy
> [417.8393 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:IsAttached
> [417.8393 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:State.Started
> [417.8467 - History.Area]: 21:59:46 16.08.4715 - [History.Area] Delete_WaterElemCorpse (000a7bea18fd40838d63a850dda49bc6)cutscene started
> [417.8488 - Etudes]: Updating etude system
> [417.8498 - Etudes]: Etude stopping: Labyrinth_SideBoss_WaterElemental_Audio
> [417.8498 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:stoping
> [417.8508 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[Labyrinth_SideBoss_WaterElemental_Audio]:IsCompleted
> [417.8508 - Etudes]: Finally completed etude: Labyrinth_SideBoss_WaterElemental_Audio
> [417.8538 - Etudes]: Etude playing: 37_FirstBigEnemy
> [417.8538 - History.Etudes]: 21:59:46 16.08.4715 - [History.Etudes] Etude[37_FirstBigEnemy]:IsPlaying
> [417.9086 - Default]: Unit leave combat: Unit[StartGame_Player_Unit]#9b22011c-06cf-4c17-8899-8b9dec6a77c4
> [417.9096 - Default]: Unit leave combat: Unit[Seelah_Companion]#4360
> [417.9096 - Default]: Unit leave combat: Unit[Camelia_Companion]#4444
> [417.9096 - Default]: Unit leave combat: Unit[Lann_Companion]#454A
> [417.9096 - Etudes]: Updating etude system
> [417.9442 - History.Combat]: 21:59:46 16.08.4715 - [History.Combat] party combat finished
> [417.9477 - TBM]: Reset tryToInitialize=False isPartyCombatStateChanged=True
> [417.9492 - TechArt]: Camera at the end: (31.6, 32.6, 104.9)
> ```
> 
> Is there anything else you need to investigate it?

Since we aren't able to reproduce, it would be helpful if you could inspect the disabled achievement(s) a little deeper. This is the base game code for "IsDisabled":

![grafik](https://github.com/user-attachments/assets/460d491d-842a-4438-a2e3-b3cfd5b66e60)

This is the ToyBox patch (basically the code that is in effect if ToyBox allow modded achievements has been turned on:

![grafik](https://github.com/user-attachments/assets/22927756-346b-4290-bc20-8c11af2888a0)

Could you figure out which of the conditions causes IsDisabled to return true?

**Comment by pehala** [comment] 2024-08-25 06:19
I think I solved it. Achievements work as intended, the important distinction is that for "Core and above" achivements it means that you can NEVER switch to lower diffuclty, and once you do you are permanently locked, even if you switch back. This was not clear from the description of achivement itself.

Other achivements seems to be working (at least for now).

I think we can close this now

**Closed** 2024-08-26 22:00 UTC
Labels: bug, question
