### ISSUE TITLE
Heavenly Host bugged by toybox

### ISSUE THREAD

**Issue by Leonion6** [xADDBx/ToyBox-Wrath#15] opened 2024-07-15 20:32 UTC
### Description of the bug

let's say, I have "speed of light" upgrade as well as "heavenly host" upgrade
1) without toybox, I cast heavenly sword and get the respective benefits (swift low-level spells and extra attack (there should be 2 but it's vanilla bug))
2) but with toybox (setting file erased before the test, so it's not any option in particular but rather toybox itself, its default state), i cast heavenly sword and don't get any benefits from "speed of light": no swift spells, no extra attack
neither for MC, nor for any companions

at the same time, "bestow the divine" without "heavenly host" works even with toybox, so it's just "heavenly host" that's bugged

### Steps To Reproduce

1) Open save file. 
2) Cast sword of heaven on mc. It works. She gets extra attack and can cast low-level spells as swift actions.
3) Reload save file.
4) Get MC the final mythic and pick "heavenly host" as sword's final upgrade. 
5) Cast sword of heaven on mc again. Now it doesn't work anymore. No extra attack, no swift-action spells. 
6) Without toybox this issue ([5]) doesn't happen. 

### Save File

[savefile_heavenlyhost.zip](https://github.com/user-attachments/files/16239889/savefile_heavenlyhost.zip)

### Toybox Version

1.5.24

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.3k

**Comment by CasDragon** [comment] 2024-07-15 22:23
Unable to replicate with your save file. Got swift spells and extra attacks with all steps.

Please provide the log files that I told you to provide in Discord, as you might have an error in there that would help us track down your issue.

**Comment by Leonion6** [comment] 2024-07-17 05:33
Which log files in particuler? I set them all to "read only" long ago because the game kept bloating them to over 1Gb size over the course of a couple of hours. 
Here is the video of the bug:
https://www.youtube.com/watch?v=KnhiC1Vy-kQ
Toybox with default settings is the only thing installed.

**Comment by xADDBx** [comment] 2024-07-20 21:41
> Which log files in particuler? I set them all to "read only" long ago because the game kept bloating them to over 1Gb size over the course of a couple of hours.
GameLogFull.txt and Player.log

**Comment by Leonion6** [comment] 2024-07-20 22:26
[logs.zip](https://github.com/user-attachments/files/16322510/logs.zip)

**Comment by xADDBx** [comment] 2024-07-21 23:31
The only things I can see is two exceptions that it can't open log files (GameLogPrev and GameLog) and a crash when you're trying to close the game.

Either the issue is not causing any exceptions or it's not being logged because the logger internally encountered those two Files Access exceptions

**Comment by CasDragon** [comment] 2024-08-06 16:30
Person in Discord says they are still having issues, so reopening in the hopes that someone else provides logs that contain information we can use or steps for us to reproduce fully.

**Comment by xADDBx** [comment] 2024-08-06 23:15
AlterAsc debugged and fixed the issue; it will be included in the next version.

**Closed** 2024-08-09 15:28 UTC
Labels: bug
